import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from 'next/font/google'

const font = Montserrat({ 
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${font.className} antialised`}>
            {children}
        </body>
    </html>
  );
}
